### ISSUE TITLE
Ship with initial support for launching specific terminal

### ISSUE THREAD

**Issue by daviwil** [Tyriar/vscode-terminal-api-example#5]
Continuing on from our Twitter discussion, I think it'd be really helpful if we could at least specify a path to the terminal to launch.  Passing arguments to it at startup would also be a bonus but I know there's currently a limitation with that on Windows.  Any chance we could make this part of the first release of the API?

**Comment by Tyriar** [comment]
Being tracked here #10917, the plan is for v1.6.0 (Sept iteration). In the meantime it's probably best to just assume it's the default and add a notice to the extension if you want to use the API.

**Comment by daviwil** [comment]
Great!  I subscribed to that issue.  Regarding the configuration setting, I had heard that there was going to be an API for extensions to manipulate configuration settings.  Do you know if that's still happening?

**Comment by Tyriar** [comment]
@daviwil haven't heard about that, I'd check out the September iteration plan when it's created.

**Comment by daviwil** [comment]
Ahhh, cool.  I was just looking for a temporary workaround until the terminal API can launch a specific terminal :)
